import { Stethoscope } from "lucide-react";

export const services = [
  {
    id: 1,
    name: "Regular Checkup",
    duration: "60 min",
    price: "$150",
    description: "Comprehensive dental examination and cleaning",
    icon: Stethoscope,
    category: "General",
    popular: true,
  },
  {
    id: 2,
    name: "Teeth Cleaning",
    duration: "45 min",
    price: "$120",
    description: "Professional dental cleaning and polishing",
    icon: Stethoscope,
    category: "General",
    popular: true,
  },
  {
    id: 3,
    name: "Cavity Filling",
    duration: "90 min",
    price: "$250",
    description: "Treatment for dental cavities and decay",
    icon: Stethoscope,
    category: "Restorative",
    popular: false,
  },
  {
    id: 4,
    name: "Teeth Whitening",
    duration: "120 min",
    price: "$400",
    description: "Professional teeth whitening treatment",
    icon: Stethoscope,
    category: "Cosmetic",
    popular: true,
  },
  {
    id: 5,
    name: "Root Canal",
    duration: "180 min",
    price: "$800",
    description: "Root canal therapy for infected teeth",
    icon: Stethoscope,
    category: "Endodontic",
    popular: false,
  },
  {
    id: 6,
    name: "Consultation",
    duration: "30 min",
    price: "$80",
    description: "Initial consultation for treatment planning",
    icon: Stethoscope,
    category: "General",
    popular: true,
  },
];
